<?php
/**
 * Form render regression tests for poule_v2 (T013).
 *
 * Tests the server-rendered HTML output of representative form templates to
 * lock down field structure, action rows, labels, validation states, and
 * status message visibility before the form restyling (T014–T017).
 *
 * These tests operate purely on HTML strings — no HTTP server is required.
 * Form templates are loaded from disk, stripped of their PHP die() guard,
 * and rendered with controlled placeholder values, then asserted using the
 * helpers from UiMarkupAssertions.
 *
 * Covered templates
 *   – modules/usercontrol/loginscreen.tpl.php  (authentication form)
 *   – modules/competitions/competition_add.tpl.php (representative add form)
 *   – modules/users/user_add.tpl.php (user add form without file upload)
 *
 * Test classes
 *   TestOfLoginFormStructure      — form element, method, action, fields, submit
 *   TestOfLoginFormStatusMessage  — {LOGIN_MSG_WRAPPER} renders message content correctly
 *   TestOfAddFormStructure        — admin add form element, method, table, buttons
 *   TestOfFormFieldRows           — label/input rows inserted via {CONTENT}
 *   TestOfFormActionRow           — submit and cancel in the action row
 *   TestOfFormValidationStates    — .error class and error message rendering
 *   TestOfFormTokenReplacement    — no unreplaced placeholder tokens in output
 *
 * @package   poule_v2
 * @author    Jaap van Boxtel
 * @copyright 2024
 */

require_once('./simpletest/autorun.php');
require_once('./ui/ui_markup_assertions.php');

// ---------------------------------------------------------------------------
// Login form rendering helpers
// ---------------------------------------------------------------------------

/**
 * Return the default placeholder values used by renderLoginForm().
 *
 * @return array<string,string>  Map of placeholder token → default value.
 */
function loginFormDefaults()
{
    return array(
        '{LANG_LOGIN}'    => 'Inloggen',
        '{LOGIN_ACTION}'  => '/?com=2&option=login',
        '{LOGIN_MSG_WRAPPER}' => '',
        '{LANG_EMAIL}'    => 'E-mail',
        '{LANG_PASSWORD}' => 'Wachtwoord',
        '{NEW_CUSTOMER}'  => '<a href="/?com=2&amp;option=new">Nieuw account</a>',
        '{LOGIN_LOST}'    => '<a href="/?com=2&amp;option=lost">Wachtwoord vergeten</a>',
        '{CSRF_TOKEN}'    => '<input type="hidden" name="csrf_token" value="test_token_abc123" />',
    );
}

/**
 * Render the login form template with the supplied placeholder replacements.
 *
 * Loads modules/usercontrol/loginscreen.tpl.php, strips the PHP die()
 * guard, and substitutes every placeholder token. Any token not supplied
 * in $replacements receives a sensible default.
 *
 * @param  array $replacements  Map of placeholder token → replacement string.
 * @return string               The fully rendered HTML string.
 */
function renderLoginForm($replacements = array())
{
    $values  = array_merge(loginFormDefaults(), $replacements);
    $tplPath = dirname(__FILE__)
             . '/../../modules/usercontrol/loginscreen.tpl.php';
    $tpl     = file_get_contents($tplPath);

    // Strip the PHP die() guard that prevents direct file access.
    $tpl = preg_replace('/^<\?php die\(\); \?>\s*/s', '', $tpl);

    return str_replace(array_keys($values), array_values($values), $tpl);
}

// ---------------------------------------------------------------------------
// Admin add form rendering helpers
// ---------------------------------------------------------------------------

/**
 * Return the default placeholder values used by renderCompetitionAddForm().
 *
 * The {CONTENT} default simulates a single text field row – the same
 * pattern generated by the module class at runtime.
 *
 * @return array<string,string>  Map of placeholder token → default value.
 */
function addFormDefaults()
{
    return array(
        '{COMPETITION_TITLE}'  => 'Competitie toevoegen',
        '{ERROR_MSG}'          => '',
        '{CONTENT}'            => '<tr><td>Naam:</td>'
                                . '<td><input type="text" name="competitionname"'
                                . ' value="" /></td></tr>',
        '{COMPETITION_ID}'     => '1',
        '{COMPETITION_COM_ID}' => '1',
        '{LANG_CANCEL}'        => 'Annuleren',
        '{LANG_SAVE}'          => 'Opslaan',
        '{CSRF_TOKEN}'         => '<input type="hidden" name="csrf_token" value="test_token_abc123" />',
    );
}

/**
 * Render the competition add form template with the supplied replacements.
 *
 * Loads modules/competitions/competition_add.tpl.php, strips the PHP
 * die() guard, and substitutes every placeholder token.
 *
 * @param  array $replacements  Map of placeholder token → replacement string.
 * @return string               The fully rendered HTML string.
 */
function renderCompetitionAddForm($replacements = array())
{
    $values  = array_merge(addFormDefaults(), $replacements);
    $tplPath = dirname(__FILE__)
             . '/../../modules/competitions/competition_add.tpl.php';
    $tpl     = file_get_contents($tplPath);

    $tpl = preg_replace('/^<\?php die\(\); \?>\s*/s', '', $tpl);

    return str_replace(array_keys($values), array_values($values), $tpl);
}

/**
 * Return the default placeholder values used by renderUserAddForm().
 *
 * @return array<string,string>  Map of placeholder token → default value.
 */
function userAddFormDefaults()
{
    return array(
        '{USER_TITLE}'   => 'Gebruiker toevoegen',
        '{ERROR_MSG}'    => '',
        '{CONTENT}'      => '<tr><td>Voornaam:</td>'
                          . '<td><input type="text" name="firstname"'
                          . ' value="" /></td></tr>',
        '{USER_COM_ID}'  => '4',
        '{LANG_CANCEL}'  => 'Annuleren',
        '{LANG_SAVE}'    => 'Opslaan',
        '{CSRF_TOKEN}'   => '<input type="hidden" name="csrf_token" value="test_token_abc123" />',
    );
}

/**
 * Render the user add form template with the supplied replacements.
 *
 * Loads modules/users/user_add.tpl.php, strips the PHP die() guard,
 * and substitutes every placeholder token.
 *
 * @param  array $replacements  Map of placeholder token → replacement string.
 * @return string               The fully rendered HTML string.
 */
function renderUserAddForm($replacements = array())
{
    $values  = array_merge(userAddFormDefaults(), $replacements);
    $tplPath = dirname(__FILE__)
             . '/../../modules/users/user_add.tpl.php';
    $tpl     = file_get_contents($tplPath);

    $tpl = preg_replace('/^<\?php die\(\); \?>\s*/s', '', $tpl);

    return str_replace(array_keys($values), array_values($values), $tpl);
}

// ===========================================================================
// 1. Login form — structure and field contract
// ===========================================================================

/**
 * Verify that the login form template renders the correct form element,
 * HTTP method, action, credential fields, and submit button.
 *
 * These assertions lock down the authentication form contract so that
 * T014 (restyle) cannot accidentally break the submit behaviour.
 */
class TestOfLoginFormStructure extends UiMarkupAssertions
{
    function testTitlePanelWithHeadingIsPresent()
    {
        $html = renderLoginForm();

        $this->assertContainsClass($html, 'title');
        $this->assertContainsTag($html, 'h2', 'Inloggen');
    }

    function testLoginFormElementIsPresent()
    {
        $html = renderLoginForm();

        $this->assertFormPresent($html);
    }

    function testLoginFormUsesPostMethod()
    {
        $html = renderLoginForm();

        $this->assertFormMethod($html, 'post');
    }

    function testLoginFormActionAttributeIsSet()
    {
        // The login form posts to a specific action URL, not an empty string.
        $html = renderLoginForm(array('{LOGIN_ACTION}' => '/?com=2&option=login'));

        $this->assertFormAction($html, 'option=login');
    }

    function testEmailTextFieldIsPresent()
    {
        $html = renderLoginForm();

        $this->assertFormField($html, 'geb');
    }

    function testPasswordFieldIsPresent()
    {
        $html = renderLoginForm();

        $this->assertFormField($html, 'wac');
    }

    function testSubmitButtonWithNameSubmitIsPresent()
    {
        $html = renderLoginForm();

        $this->assertFormSubmitButton($html, 'Inloggen');
        $this->assertHtmlContains($html, 'name="submit"');
    }

    function testFieldsAreWrappedInATableListElement()
    {
        $html = renderLoginForm();

        $this->assertListTable($html);
    }

    function testEmailLabelIsVisible()
    {
        $html = renderLoginForm();

        $this->assertFormLabel($html, 'E-mail');
    }

    function testPasswordLabelIsVisible()
    {
        $html = renderLoginForm();

        $this->assertFormLabel($html, 'Wachtwoord');
    }
}

// ===========================================================================
// 2. Login form — status message rendering
// ===========================================================================

/**
 * Verify that the {LOGIN_MSG_WRAPPER} placeholder renders correctly for the three
 * distinct message states used by the authentication flow:
 *
 *   – empty      (no message)
 *   – error text  (login failure feedback)
 *   – alert HTML  (Bootstrap-aligned status)
 */
class TestOfLoginFormStatusMessage extends UiMarkupAssertions
{
    function testEmptyLoginMsgProducesNoAlertElement()
    {
        $html = renderLoginForm(array('{LOGIN_MSG_WRAPPER}' => ''));

        $this->assertNoAlert($html);
    }

    function testLoginMsgWithPlainTextRendersTextInOutput()
    {
        $html = renderLoginForm(array(
            '{LOGIN_MSG_WRAPPER}' => 'Ongeldig wachtwoord of e-mail adres.',
        ));

        $this->assertHtmlContains(
            $html,
            'Ongeldig wachtwoord of e-mail adres.',
            'Expected the login error text to appear in the rendered output.'
        );
    }

    function testLoginMsgWithAlertHtmlRendersAlertElement()
    {
        $alertHtml = '<div class="alert alert-danger">Inloggen mislukt.</div>';
        $html      = renderLoginForm(array('{LOGIN_MSG_WRAPPER}' => $alertHtml));

        $this->assertDangerAlert($html);
        $this->assertAlertContains($html, 'Inloggen mislukt.');
    }

    function testLoginLostAreaIsPresent()
    {
        $html = renderLoginForm();

        $this->assertHtmlContains(
            $html,
            'id="login_lost"',
            'Expected the #login_lost recovery area to be present.'
        );
    }

    function testLoginLostAreaContainsNewCustomerAndLostPasswordLinks()
    {
        $html = renderLoginForm();

        // Both the new-account and lost-password links must appear inside
        // the recovery area div so users can self-serve.
        $this->assertHtmlContains(
            $html,
            'option=new',
            'Expected a new-account link in the #login_lost area.'
        );
        $this->assertHtmlContains(
            $html,
            'option=lost',
            'Expected a lost-password link in the #login_lost area.'
        );
    }
}

// ===========================================================================
// 3. Admin add form — structure and submit contract
// ===========================================================================

/**
 * Verify that the representative admin add form (competition_add) renders
 * the correct form element, HTTP method, self-post action, list table,
 * and both submit and cancel buttons.
 *
 * These assertions lock down the admin form contract so that T015/T016
 * (restyle) cannot accidentally change the submission behaviour.
 */
class TestOfAddFormStructure extends UiMarkupAssertions
{
    function testTitlePanelWithHeadingIsPresent()
    {
        $html = renderCompetitionAddForm();

        $this->assertContainsClass($html, 'title');
        $this->assertContainsTag($html, 'h2', 'Competitie toevoegen');
    }

    function testFormElementIsPresent()
    {
        $html = renderCompetitionAddForm();

        $this->assertFormPresent($html);
    }

    function testFormUsesPostMethod()
    {
        $html = renderCompetitionAddForm();

        $this->assertFormMethod($html, 'post');
    }

    function testFormActionIsEmptyForSelfPost()
    {
        // Admin forms use action="" to post back to the current URL.
        $html = renderCompetitionAddForm();

        $this->assertHtmlContains(
            $html,
            'action=""',
            'Expected the admin add form to use action="" (self-post).'
        );
    }

    function testFieldsAreWrappedInATableListElement()
    {
        $html = renderCompetitionAddForm();

        $this->assertListTable($html);
    }

    function testSubmitButtonWithNameSubmitIsPresent()
    {
        $html = renderCompetitionAddForm();

        $this->assertFormSubmitButton($html, 'Opslaan');
        $this->assertHtmlContains($html, 'name="submit"');
    }

    function testCancelButtonOfTypeButtonIsPresent()
    {
        $html = renderCompetitionAddForm();

        $this->assertFormCancelButton($html);
    }

    function testErrorMessageDivIsPresent()
    {
        // With the card-based message pattern, the error card is only rendered
        // when a message is provided. Verify the form card wrapper is present.
        $html = renderCompetitionAddForm();

        $this->assertContainsClass(
            $html,
            'card',
            'Expected the .card wrapper to be present in the rendered form.'
        );
    }

    function testUserAddFormUsesPostMethodWithEmptyAction()
    {
        // Verify the same structural contract holds for the user add form,
        // which does not use enctype="multipart/form-data".
        $html = renderUserAddForm();

        $this->assertFormPresent($html);
        $this->assertFormMethod($html, 'post');
        $this->assertHtmlContains($html, 'action=""');
    }
}

// ===========================================================================
// 4. Form field rows — {CONTENT} insertion and label visibility
// ===========================================================================

/**
 * Verify that field rows inserted through the {CONTENT} placeholder render
 * inside the form table and preserve the label/input pairing that the
 * module classes generate.
 *
 * These tests use controlled HTML snippets that mirror the row format
 * produced by competitions.class.php, users.class.php, etc.
 */
class TestOfFormFieldRows extends UiMarkupAssertions
{
    function testSingleTextFieldRowRendersInsideForm()
    {
        $fieldRow = '<tr><td>Naam:</td>'
                  . '<td><input type="text" name="competitionname" value="" /></td>'
                  . '</tr>';
        $html = renderCompetitionAddForm(array('{CONTENT}' => $fieldRow));

        $this->assertFormField($html, 'competitionname');
    }

    function testFieldLabelAppearsAlongsideInput()
    {
        $fieldRow = '<tr><td>Omschrijving:</td>'
                  . '<td><input type="text" name="description" value="" /></td>'
                  . '</tr>';
        $html = renderCompetitionAddForm(array('{CONTENT}' => $fieldRow));

        $this->assertHtmlContains(
            $html,
            'Omschrijving:',
            'Expected the field label to appear in the rendered form output.'
        );
        $this->assertFormField($html, 'description');
    }

    function testMultipleFieldRowsAllRenderCorrectly()
    {
        $content = '<tr><td>Voornaam:</td>'
                 . '<td><input type="text" name="firstname" value="" /></td></tr>'
                 . '<tr><td>Achternaam:</td>'
                 . '<td><input type="text" name="lastname" value="" /></td></tr>'
                 . '<tr><td>E-mail:</td>'
                 . '<td><input type="text" name="emailaddress" value="" /></td></tr>';
        $html = renderUserAddForm(array('{CONTENT}' => $content));

        $this->assertFormField($html, 'firstname');
        $this->assertFormField($html, 'lastname');
        $this->assertFormField($html, 'emailaddress');
    }

    function testSelectFieldRowRendersInsideForm()
    {
        $fieldRow = '<tr><td>Status:</td>'
                  . '<td><select name="status">'
                  . '<option value="1">Actief</option>'
                  . '<option value="0">Inactief</option>'
                  . '</select></td></tr>';
        $html = renderCompetitionAddForm(array('{CONTENT}' => $fieldRow));

        $this->assertFormField($html, 'status');
    }

    function testHiddenFieldIsPreservedInOutput()
    {
        // Hidden fields in {CONTENT} must survive template substitution
        // intact because they carry business-logic values.
        $fieldRow = '<tr><td colspan="2">'
                  . '<input type="hidden" name="competition_id" value="42" />'
                  . '</td></tr>';
        $html = renderCompetitionAddForm(array('{CONTENT}' => $fieldRow));

        $this->assertHiddenField($html, 'competition_id');
    }
}

// ===========================================================================
// 5. Form action row — submit and cancel button placement
// ===========================================================================

/**
 * Verify the action row at the bottom of admin add forms renders the submit
 * and cancel buttons inside a right-aligned table cell.
 *
 * The action row is the last data row in the table, immediately before the
 * closing spacer row, and serves as the primary call-to-action for the form.
 */
class TestOfFormActionRow extends UiMarkupAssertions
{
    function testActionRowContainsBothSubmitAndCancelButtons()
    {
        $html = renderCompetitionAddForm();

        $this->assertFormSubmitButton($html);
        $this->assertFormCancelButton($html);
    }

    function testActionRowCellIsRightAligned()
    {
        // The action row uses inline style "text-align: right;" to right-align
        // the primary/secondary buttons – a key visual contract for the forms.
        $html = renderCompetitionAddForm();

        $this->assertHtmlContains(
            $html,
            'text-align: right;',
            'Expected the action row cell to use text-align: right; for button alignment.'
        );
    }

    function testSubmitButtonHasNameSubmit()
    {
        $html = renderCompetitionAddForm();

        // The submit button must keep name="submit" so that the server-side
        // handler can detect the form submission correctly.
        $this->assertHtmlContains($html, 'name="submit"');
    }

    function testCancelButtonHasTypeButton()
    {
        // Cancel buttons use type="button" to prevent accidental form
        // submission; their onclick handler handles the navigation.
        $html = renderCompetitionAddForm();

        $this->assertHtmlContains(
            $html,
            'type="button"',
            'Expected the cancel button to use type="button".'
        );
    }

    function testCancelButtonOnclickNavigatesToOverview()
    {
        // The cancel button must have an onclick that navigates back to
        // the module overview so users can discard changes without
        // submitting the form.
        $html = renderCompetitionAddForm(array(
            '{COMPETITION_ID}'     => '3',
            '{COMPETITION_COM_ID}' => '1',
        ));

        $this->assertHtmlContains(
            $html,
            'onclick=',
            'Expected the cancel button to carry an onclick navigation handler.'
        );
        $this->assertHtmlContains(
            $html,
            'competition=3',
            'Expected the cancel onclick to include the competition context.'
        );
    }

    function testUserAddFormActionRowContainsBothButtons()
    {
        // Verify the same action-row contract holds for the user add form.
        $html = renderUserAddForm();

        $this->assertFormSubmitButton($html);
        $this->assertFormCancelButton($html);
    }
}

// ===========================================================================
// 6. Form validation states — error class and error message rendering
// ===========================================================================

/**
 * Verify that input error states and error message containers render
 * correctly so that the restyling (T014–T016) preserves validation
 * feedback visibility.
 */
class TestOfFormValidationStates extends UiMarkupAssertions
{
    function testInputWithErrorClassIsDetectedAsErrorState()
    {
        $errorRow = '<tr><td>Naam:</td>'
                  . '<td><input class="error" type="text" name="competitionname"'
                  . ' value="" /></td></tr>';
        $html = renderCompetitionAddForm(array('{CONTENT}' => $errorRow));

        $this->assertInputErrorState($html);
    }

    function testInputWithoutErrorClassIsDetectedAsCleanState()
    {
        $cleanRow = '<tr><td>Naam:</td>'
                  . '<td><input type="text" name="competitionname"'
                  . ' value="" /></td></tr>';
        $html = renderCompetitionAddForm(array('{CONTENT}' => $cleanRow));

        $this->assertNoInputErrorState($html);
    }

    function testSelectWithErrorClassIsDetectedAsErrorState()
    {
        $errorRow = '<tr><td>Status:</td>'
                  . '<td><select class="error" name="status">'
                  . '<option value="">-- kies --</option>'
                  . '</select></td></tr>';
        $html = renderCompetitionAddForm(array('{CONTENT}' => $errorRow));

        $this->assertInputErrorState($html);
    }

    function testErrorMsgWithTextRendersErrorTextInOutput()
    {
        $html = renderCompetitionAddForm(array(
            '{ERROR_MSG}' => 'Vul alle verplichte velden in.',
        ));

        $this->assertHtmlContains(
            $html,
            'Vul alle verplichte velden in.',
            'Expected the server-side error message text to appear in output.'
        );
    }

    function testErrorMsgWithAlertHtmlRendersAlertElement()
    {
        $alertHtml = '<div class="alert alert-danger">Naam is verplicht.</div>';
        $html      = renderCompetitionAddForm(array('{ERROR_MSG}' => $alertHtml));

        $this->assertDangerAlert($html);
        $this->assertAlertContains($html, 'Naam is verplicht.');
    }

    function testUserMsgOnUserFormRendersStatusAlert()
    {
        $alertHtml = '<div class="alert alert-success">Gebruiker opgeslagen.</div>';
        $html      = renderUserAddForm(array('{ERROR_MSG}' => $alertHtml));

        $this->assertSuccessAlert($html);
        $this->assertAlertContains($html, 'Gebruiker opgeslagen.');
    }
}

// ===========================================================================
// 7. Token replacement — no unreplaced placeholder tokens
// ===========================================================================

/**
 * Verify that every placeholder token is removed from the rendered output.
 *
 * An unreplaced token (e.g., the literal string '{LANG_LOGIN}') in the
 * final HTML indicates a missing substitution and would be visible to
 * end-users as broken markup.
 */
class TestOfFormTokenReplacement extends UiMarkupAssertions
{
    function testNoUnreplacedTokensInLoginForm()
    {
        $html   = renderLoginForm();
        $tokens = array_keys(loginFormDefaults());

        foreach ($tokens as $token) {
            $this->assertHtmlNotContains(
                $html,
                $token,
                "Placeholder {$token} was not replaced in the login form."
            );
        }
    }

    function testNoUnreplacedTokensInCompetitionAddForm()
    {
        $html   = renderCompetitionAddForm();
        $tokens = array_keys(addFormDefaults());

        foreach ($tokens as $token) {
            $this->assertHtmlNotContains(
                $html,
                $token,
                "Placeholder {$token} was not replaced in the competition add form."
            );
        }
    }

    function testNoUnreplacedTokensInUserAddForm()
    {
        $html   = renderUserAddForm();
        $tokens = array_keys(userAddFormDefaults());

        foreach ($tokens as $token) {
            $this->assertHtmlNotContains(
                $html,
                $token,
                "Placeholder {$token} was not replaced in the user add form."
            );
        }
    }
}

// ===========================================================================
// 8. CSRF token — presence and structure across all representative forms
// ===========================================================================

/**
 * Verify that every rendered form contains a CSRF hidden field with the
 * correct name attribute.  This locks down the CSRF protection contract
 * added in VULN-007 so that future template refactors cannot silently
 * remove the token.
 */
class TestOfCsrfTokenPresence extends UiMarkupAssertions
{
    function testLoginFormContainsCsrfHiddenField()
    {
        $html = renderLoginForm();

        $this->assertHtmlContains(
            $html,
            'name="csrf_token"',
            'Login form must contain a hidden csrf_token field.'
        );
        $this->assertHtmlContains(
            $html,
            'type="hidden"',
            'Login form csrf_token must be a hidden input.'
        );
    }

    function testCompetitionAddFormContainsCsrfHiddenField()
    {
        $html = renderCompetitionAddForm();

        $this->assertHtmlContains(
            $html,
            'name="csrf_token"',
            'Competition add form must contain a hidden csrf_token field.'
        );
    }

    function testUserAddFormContainsCsrfHiddenField()
    {
        $html = renderUserAddForm();

        $this->assertHtmlContains(
            $html,
            'name="csrf_token"',
            'User add form must contain a hidden csrf_token field.'
        );
    }

    function testCsrfTokenPlaceholderIsReplacedInLoginForm()
    {
        $html = renderLoginForm();

        $this->assertHtmlNotContains(
            $html,
            '{CSRF_TOKEN}',
            'The {CSRF_TOKEN} placeholder must be replaced in the login form.'
        );
    }

    function testCsrfTokenPlaceholderIsReplacedInCompetitionAddForm()
    {
        $html = renderCompetitionAddForm();

        $this->assertHtmlNotContains(
            $html,
            '{CSRF_TOKEN}',
            'The {CSRF_TOKEN} placeholder must be replaced in the competition add form.'
        );
    }

    function testCsrfTokenPlaceholderIsReplacedInUserAddForm()
    {
        $html = renderUserAddForm();

        $this->assertHtmlNotContains(
            $html,
            '{CSRF_TOKEN}',
            'The {CSRF_TOKEN} placeholder must be replaced in the user add form.'
        );
    }
}
?>
